class AppConstants{

 static String fontFamily = 'Poppins';
 static String secondFontFamily = 'Quicksand';
 static String skillHeadlineText = 'In my learning journey and professional work since 2019 in Flutter, from designing mobile UIs, integrating backends, and creating beautiful animated designs to improving their responsiveness and performance, as well as deploying them on the Play Store and App Store, I have acquired valuable skills.';
 static String flutterSkillText = "With over 5 years of hands-on Flutter expertise, I transform ideas into pixel-perfect, high-performance apps. From sleek UI/UX to seamless Firebase and API integrations, I build dynamic, scalable, and intuitive mobile experiences. Passionate about animations, state management, and innovation, I push the boundaries of Flutter magic. Your vision—my code. Let’s create something extraordinary!";
 static String androidSkillText = "With over 5 years of hands-on Flutter expertise, I transform ideas into pixel-perfect, high-performance apps. From sleek UI/UX to seamless Firebase and API integrations, I build dynamic, scalable, and intuitive mobile experiences. Passionate about animations, state management, and innovation, I push the boundaries of Flutter magic. Your vision—my code. Let’s create something extraordinary!";
 static String iosSkillText = "With over 5 years of hands-on Flutter expertise, I transform ideas into pixel-perfect, high-performance apps. From sleek UI/UX to seamless Firebase and API integrations, I build dynamic, scalable, and intuitive mobile experiences. Passionate about animations, state management, and innovation, I push the boundaries of Flutter magic. Your vision—my code. Let’s create something extraordinary!";
 static String firebaseSkillText = "With over 5 years of hands-on Flutter expertise, I transform ideas into pixel-perfect, high-performance apps. From sleek UI/UX to seamless Firebase and API integrations, I build dynamic, scalable, and intuitive mobile experiences. Passionate about animations, state management, and innovation, I push the boundaries of Flutter magic. Your vision—my code. Let’s create something extraordinary!";
 static String githubSkillText = "With over 5 years of hands-on Flutter expertise, I transform ideas into pixel-perfect, high-performance apps. From sleek UI/UX to seamless Firebase and API integrations, I build dynamic, scalable, and intuitive mobile experiences. Passionate about animations, state management, and innovation, I push the boundaries of Flutter magic. Your vision—my code. Let’s create something extraordinary!";
 static String jiraSkillText = "With over 5 years of hands-on Flutter expertise, I transform ideas into pixel-perfect, high-performance apps. From sleek UI/UX to seamless Firebase and API integrations, I build dynamic, scalable, and intuitive mobile experiences. Passionate about animations, state management, and innovation, I push the boundaries of Flutter magic. Your vision—my code. Let’s create something extraordinary!";
 static String bitbucketSkillText = "With over 5 years of hands-on Flutter expertise, I transform ideas into pixel-perfect, high-performance apps. From sleek UI/UX to seamless Firebase and API integrations, I build dynamic, scalable, and intuitive mobile experiences. Passionate about animations, state management, and innovation, I push the boundaries of Flutter magic. Your vision—my code. Let’s create something extraordinary!";
}